### PR TITLE
Stabilise openshift 4.15 spec & add openshift 4.16-experimental spec

### PR DESCRIPTION
**Pull request by travier**
docs: Fix openshift v4.14 generated docs

Fixes: https://github.com/coreos/butane/commit/186b8e8a7e2183b470f3edee967ca3da12761153

---

openshift/v4.15: Stabilize 4.15.0 spec

---

openshift/v4.15: Use fcos 1.5 & ignition 3.4 specs

Stabilise openshift 4.14.0 spec on fcos 1.5 and ignition 3.4 stable
specs. fcos 1.6 & ignition 3.5 are still experimental.

---

internal/doc/butane: Fix whitespace

Fixes: 0d2fa0f spec/v1.6: Add support for boot_device sugar on s390x

---

openshift/v4.15: Remove GRUB password support

---

openshift/v4_16_exp: Add 4.16.0-experimental spec

--

Fixes: https://github.com/coreos/butane/issues/511
Based on https://github.com/coreos/butane/pull/513 for convenience.

### CODE REVIEW

**Comment by travier** [comment]
See also https://github.com/coreos/butane/issues/515

**Review by prestist — COMMENTED** [review]
Overall, its looks good, and thank you for doing this.

I have a few small picks about the structuring of your commits, it would help readability for me. Not sure if it's a nessary change though. 

Looking at your commit structure
[docs: Fix openshift v4.14 generated docs]
[docs: Mark grub section as unsupported]
[internal/doc/butane: Fix whitespace]
[openshift/v4.15: Stabilize 4.15.0 spec]
[openshift/v4.15: Use fcos 1.5 & ignition 3.4 specs]
[openshift/v4.15: Remove GRUB password support]
[openshift/v4_16_exp: Add 4.16.0-experimental spec]

I think it would be better to be 
[docs: Fix openshift v4.14 generated docs] ++ [docs: Mark grub section as unsupported]
[internal/doc/butane: Fix whitespace]
[openshift/v4_15_exp: rename to v4_16_exp]
[openshift/v4_15: copy from v4_16_exp]
[Stabilize openshift 4.15.0; create openshift 4.16.0-experimental]
[openshift/v4.15: Remove GRUB password support]

wdyt?

**Comment by prestist** [comment]
Also nit Stabilize not Stabilise just because past pr's tend to use Stabilize

**Review by prestist — APPROVED** [review]
As there are not any changes that must happen to merge, and there is a timeline. Lets merge as is. 
LGTM

**Comment by travier** [comment]
I followed the steps from https://github.com/coreos/butane/issues/511. Maybe we could revisit them at some later time. I don't have the full context for the order but I can see some logic behind it (mostly to avoid mistakes).

**Pull request merged**
