### PR TITLE
Ignition spec bump

### PR DESCRIPTION
**Pull request by prestist**
https://github.com/coreos/butane/issues/558

### CODE REVIEW

**Comment by travier** [comment]
Hum, it looks like you're trying to stabilize a lot of variants in this PR at the same time.

**Comment by travier** [comment]
I had copied the entire template in the issue but we don't need to do it all.

We only need to bump the experimental versions.

**Comment by travier** [comment]
So, I took another look at this and what I would do is to only bump ignition to 3.6-exp first in all the experimental config variants.

Then in https://github.com/coreos/butane/issues/559, we would stabilise the base, fcos and 4.18 config variants on 3.5.0 and keep all of the other variants on the new exp base & fcos ones.

**Comment by prestist** [comment]
spoke with @travier ; dialing back changes to go into independent prs, https://github.com/coreos/butane/issues/550#issuecomment-2488967415 . You can see that this pr is simply an import of the latest ignition with its now stabilized 3.5, which resulted in some new docs, see second commit.

**Comment by travier** [comment]
I considered splitting the vendor part from the changes in the first commit but that would have made it non-atomic / harder to bissect while making it easier to distinct which changes were manual vs the vendor code.

But overall it's the same result so let's go with that as it's bissectable.

**Review by travier — APPROVED** [review]

**Comment by travier** [comment]
Hum, maybe we should move the spec that we are not going to stabilize directly to 3.6.0-exp in this one.

**Comment by prestist** [comment]
> Hum, maybe we should move the specs that we are not going to stabilize directly to 3.6.0-exp in this one.

Thats fair, I was thinking I would do that when adding the new base, which I assumed I would do with other sterilizations (fcos)

**Pull request merged**
